/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.Product;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author Abhi
 */
public class CreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJpanel
     */
    private Product product;
    public CreateJpanel(Product product) {
        initComponents();
        this.product=product;
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CreatepersonalprofileJlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FirstnameJlabel = new javax.swing.JLabel();
        FirstnameJtextfield = new javax.swing.JTextField();
        lastnameJlabel = new javax.swing.JLabel();
        LastnameJtextfield = new javax.swing.JTextField();
        PhonenumberJlabel = new javax.swing.JLabel();
        PhonenumberJtextfiled = new javax.swing.JTextField();
        SsnJlabel = new javax.swing.JLabel();
        SsnJtextfield = new javax.swing.JTextField();
        DobJlabel = new javax.swing.JLabel();
        DobJtextfield = new javax.swing.JTextField();
        AgeJlabel = new javax.swing.JLabel();
        AgeJtextfield = new javax.swing.JTextField();
        GeneralinformationJlabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        AddressinformationJlabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        StreetJlabel = new javax.swing.JLabel();
        StreetJtextField = new javax.swing.JTextField();
        CityJlabel = new javax.swing.JLabel();
        CityJtextField = new javax.swing.JTextField();
        StateJlabel = new javax.swing.JLabel();
        StateJtextField = new javax.swing.JTextField();
        ZipcodeJlabel = new javax.swing.JLabel();
        ZipcodeJtextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BankaccountinformationJlabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Bankname1Jlabel = new javax.swing.JLabel();
        Bankname1JtextField = new javax.swing.JTextField();
        Type1jlabel = new javax.swing.JLabel();
        balance1Jlabel = new javax.swing.JLabel();
        Balance1Jtextfield = new javax.swing.JTextField();
        Account1Jlabel = new javax.swing.JLabel();
        Account1Jtextfield = new javax.swing.JTextField();
        Routing1jlabel = new javax.swing.JLabel();
        Routing1Jtextfield = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Bankname2Jlabel1 = new javax.swing.JLabel();
        Account2jlabel = new javax.swing.JLabel();
        Account2JextField = new javax.swing.JTextField();
        Bankname2JtextField = new javax.swing.JTextField();
        Type2Jlabel = new javax.swing.JLabel();
        Routing2Jlabel = new javax.swing.JLabel();
        Routing2JtextField = new javax.swing.JTextField();
        Balance2Jtextfield = new javax.swing.JTextField();
        balance2Jlabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        DriverlicenseinformationJlabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        AdddriverlicenseJbutton = new javax.swing.JButton();
        MedicalinformationJlabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        MedicalrecordJlabel = new javax.swing.JLabel();
        MedicalrecordJtextfield = new javax.swing.JTextField();
        Alergy1Jlabel = new javax.swing.JLabel();
        Alergy1JtextField = new javax.swing.JTextField();
        Alregy2label = new javax.swing.JLabel();
        Alergy2Jtextfield = new javax.swing.JTextField();
        Alergy3Jlabel = new javax.swing.JLabel();
        Alergy3Jtextfelid = new javax.swing.JTextField();
        CreateprofileJbutton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        imagejLabel = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        CreatepersonalprofileJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        CreatepersonalprofileJlabel.setText("CREATE A PERSONAL PROFILE");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        FirstnameJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        FirstnameJlabel.setText("First Name:");

        FirstnameJtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameJtextfieldActionPerformed(evt);
            }
        });

        lastnameJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lastnameJlabel.setText("Last Name:");

        PhonenumberJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        PhonenumberJlabel.setText("Phone Number:");

        SsnJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        SsnJlabel.setText("SSN:");

        DobJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        DobJlabel.setText("DOB(dd/mm/yyyy)");

        AgeJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        AgeJlabel.setText("Age:");

        GeneralinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        GeneralinformationJlabel.setText("1.GENERAL INFORMATION:");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        AddressinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        AddressinformationJlabel.setText("2.ADDRESS INFORMATION:");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        StreetJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        StreetJlabel.setText("Street:");

        CityJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        CityJlabel.setText("City:");

        StateJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        StateJlabel.setText("State:");

        ZipcodeJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        ZipcodeJlabel.setText("Zipcode:");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        BankaccountinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        BankaccountinformationJlabel.setText("3.BANK ACCOUNT INFORMATION:");

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        Bankname1Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Bankname1Jlabel.setText("Bank Name:");

        Type1jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Type1jlabel.setText("Type(Saving/Checking):");

        balance1Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        balance1Jlabel.setText("Balance:");

        Account1Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Account1Jlabel.setText("Account#:");

        Routing1jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Routing1jlabel.setText("Routing:");

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        Bankname2Jlabel1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Bankname2Jlabel1.setText("Bank Name:");

        Account2jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Account2jlabel.setText("Account#:");

        Type2Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Type2Jlabel.setText("Type(Saving/Checking):");

        Routing2Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Routing2Jlabel.setText("Routing:");

        balance2Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        balance2Jlabel.setText("Balance:");

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        DriverlicenseinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        DriverlicenseinformationJlabel.setText("4.DRIVIER LICENSE INFORMATION:");

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        AdddriverlicenseJbutton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        AdddriverlicenseJbutton.setText("Add driver license");
        AdddriverlicenseJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdddriverlicenseJbuttonActionPerformed(evt);
            }
        });

        MedicalinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        MedicalinformationJlabel.setText("5.MEDICAL INFORMATION");

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        MedicalrecordJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        MedicalrecordJlabel.setText("Medical Record#:");

        Alergy1Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Alergy1Jlabel.setText("Allergy1:");

        Alregy2label.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Alregy2label.setText("Alergy2:");

        Alergy3Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Alergy3Jlabel.setText("Alergy3:");

        CreateprofileJbutton.setBackground(new java.awt.Color(153, 153, 153));
        CreateprofileJbutton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        CreateprofileJbutton.setText("CREATE PROFILE");
        CreateprofileJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateprofileJbuttonActionPerformed(evt);
            }
        });

        jComboBox1.setMaximumRowCount(2);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings", "Checking" }));

        jComboBox2.setMaximumRowCount(2);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Savings", "Checking" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        imagejLabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        imagejLabel.setText("No image uploaded");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(CreatepersonalprofileJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SsnJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SsnJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FirstnameJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lastnameJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DobJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DobJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PhonenumberJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhonenumberJtextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AgeJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgeJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GeneralinformationJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddressinformationJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(StreetJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StreetJtextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(CityJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CityJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(StateJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StateJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(ZipcodeJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZipcodeJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 224, Short.MAX_VALUE))
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator9)
            .addComponent(jSeparator10)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Account2jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Account2JextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bankname2Jlabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bankname2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Type2Jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(balance2Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Balance2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Routing2Jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Routing2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BankaccountinformationJlabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Account1Jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Account1Jtextfield))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Bankname1Jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bankname1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Type1jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(balance1Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Balance1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Routing1jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Routing1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DriverlicenseinformationJlabel)
                                .addGap(76, 76, 76)
                                .addComponent(AdddriverlicenseJbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagejLabel))
                            .addComponent(MedicalinformationJlabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MedicalrecordJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MedicalrecordJtextfield))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Alergy1Jlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alergy1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Alregy2label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Alergy2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)
                                        .addComponent(Alergy3Jlabel))
                                    .addComponent(CreateprofileJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alergy3Jtextfelid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatepersonalprofileJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameJlabel)
                            .addComponent(LastnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhonenumberJtextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhonenumberJlabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstnameJlabel)
                                .addComponent(FirstnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SsnJlabel)
                            .addComponent(SsnJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DobJlabel)
                            .addComponent(DobJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeJlabel)
                            .addComponent(AgeJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddressinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetJlabel)
                    .addComponent(StreetJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityJlabel)
                    .addComponent(StateJlabel)
                    .addComponent(StateJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipcodeJlabel)
                    .addComponent(ZipcodeJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BankaccountinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bankname1Jlabel)
                        .addComponent(Bankname1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Type1jlabel)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(balance1Jlabel)
                        .addComponent(Balance1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account1Jlabel)
                    .addComponent(Account1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Routing1jlabel)
                    .addComponent(Routing1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bankname2Jlabel1)
                        .addComponent(Bankname2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Type2Jlabel)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Balance2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(balance2Jlabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account2jlabel)
                    .addComponent(Account2JextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Routing2Jlabel)
                    .addComponent(Routing2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverlicenseinformationJlabel)
                    .addComponent(AdddriverlicenseJbutton)
                    .addComponent(imagejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalrecordJlabel)
                    .addComponent(MedicalrecordJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy1Jlabel)
                    .addComponent(Alergy1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alregy2label)
                    .addComponent(Alergy2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alergy3Jlabel)
                    .addComponent(Alergy3Jtextfelid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateprofileJbutton)
                .addContainerGap(4153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnameJtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameJtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameJtextfieldActionPerformed

    private void CreateprofileJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateprofileJbuttonActionPerformed
        // TODO add your handling code here:
        product.setFirstname(FirstnameJtextfield.getText());
        product.setLastname(LastnameJtextfield.getText());
        product.setPhonenumber(PhonenumberJtextfiled.getText());
        product.setSsn(SsnJtextfield.getText());
        product.setDob(DobJtextfield.getText());
        product.setAge(AgeJtextfield.getText());
        product.setStreet(StreetJtextField.getText());
        product.setCity(CityJtextField.getText());
        product.setState(StateJtextField.getText());
        product.setBankname1(Bankname1JtextField.getText());
        product.setBalance1(Balance1Jtextfield.getText());
        product.setRouting1(Routing1Jtextfield.getText());
        product.setAccount1(Account1Jtextfield.getText());
        product.setBankname2(Bankname2JtextField.getText());
        product.setBalance2(Balance2Jtextfield.getText());
        product.setRouting2(Routing2JtextField.getText());
        product.setAccount2(Account2JextField.getText());
        product.setMedicalrecord(MedicalrecordJtextfield.getText());
        product.setAlergy1(Alergy1JtextField.getText());
        product.setAlergy2(Alergy2Jtextfield.getText());
        product.setAlergy3(Alergy3Jtextfelid.getText());
        
        int i=jComboBox1.getSelectedIndex();
        
        if(i == 0){
            product.setType1("Saving");
        }else{
            product.setType1("Checking");
        }
        
        int j=jComboBox2.getSelectedIndex();
        
        if(j == 0){
            product.setType2("Saving");
        }else{
            product.setType2("Checking");
        }
        
        JOptionPane.showMessageDialog(null,"Create Product Successfully");
        
       
        
    }//GEN-LAST:event_CreateprofileJbuttonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void AdddriverlicenseJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdddriverlicenseJbuttonActionPerformed
        // TODO add your handling code here:
        String path=new String();
        JFileChooser chooser=new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = chooser.showOpenDialog(null);
        if(i== chooser.APPROVE_OPTION){
            path = chooser.getSelectedFile().getAbsolutePath();
            product.setLicense(path);
            imagejLabel.setText("Image Uploaded");
        }
            else{
                    JOptionPane.showMessageDialog(null,"No file was selected");
                    
                }
        ImageIcon image = new ImageIcon(path);
                image.setImage(image.getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                imagejLabel.setIcon(image);
                
                  
            
       
    }//GEN-LAST:event_AdddriverlicenseJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account1Jlabel;
    private javax.swing.JTextField Account1Jtextfield;
    private javax.swing.JTextField Account2JextField;
    private javax.swing.JLabel Account2jlabel;
    private javax.swing.JButton AdddriverlicenseJbutton;
    private javax.swing.JLabel AddressinformationJlabel;
    private javax.swing.JLabel AgeJlabel;
    private javax.swing.JTextField AgeJtextfield;
    private javax.swing.JLabel Alergy1Jlabel;
    private javax.swing.JTextField Alergy1JtextField;
    private javax.swing.JTextField Alergy2Jtextfield;
    private javax.swing.JLabel Alergy3Jlabel;
    private javax.swing.JTextField Alergy3Jtextfelid;
    private javax.swing.JLabel Alregy2label;
    private javax.swing.JTextField Balance1Jtextfield;
    private javax.swing.JTextField Balance2Jtextfield;
    private javax.swing.JLabel BankaccountinformationJlabel;
    private javax.swing.JLabel Bankname1Jlabel;
    private javax.swing.JTextField Bankname1JtextField;
    private javax.swing.JLabel Bankname2Jlabel1;
    private javax.swing.JTextField Bankname2JtextField;
    private javax.swing.JLabel CityJlabel;
    private javax.swing.JTextField CityJtextField;
    private javax.swing.JLabel CreatepersonalprofileJlabel;
    private javax.swing.JButton CreateprofileJbutton;
    private javax.swing.JLabel DobJlabel;
    private javax.swing.JTextField DobJtextfield;
    private javax.swing.JLabel DriverlicenseinformationJlabel;
    private javax.swing.JLabel FirstnameJlabel;
    private javax.swing.JTextField FirstnameJtextfield;
    private javax.swing.JLabel GeneralinformationJlabel;
    private javax.swing.JTextField LastnameJtextfield;
    private javax.swing.JLabel MedicalinformationJlabel;
    private javax.swing.JLabel MedicalrecordJlabel;
    private javax.swing.JTextField MedicalrecordJtextfield;
    private javax.swing.JLabel PhonenumberJlabel;
    private javax.swing.JTextField PhonenumberJtextfiled;
    private javax.swing.JTextField Routing1Jtextfield;
    private javax.swing.JLabel Routing1jlabel;
    private javax.swing.JLabel Routing2Jlabel;
    private javax.swing.JTextField Routing2JtextField;
    private javax.swing.JLabel SsnJlabel;
    private javax.swing.JTextField SsnJtextfield;
    private javax.swing.JLabel StateJlabel;
    private javax.swing.JTextField StateJtextField;
    private javax.swing.JLabel StreetJlabel;
    private javax.swing.JTextField StreetJtextField;
    private javax.swing.JLabel Type1jlabel;
    private javax.swing.JLabel Type2Jlabel;
    private javax.swing.JLabel ZipcodeJlabel;
    private javax.swing.JTextField ZipcodeJtextField;
    private javax.swing.JLabel balance1Jlabel;
    private javax.swing.JLabel balance2Jlabel;
    private javax.swing.JLabel imagejLabel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastnameJlabel;
    // End of variables declaration//GEN-END:variables
}
