/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Profile.Product;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.*;
/**
 *
 * @author Abhi
 */
public class ViewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     */
    public ViewJpanel(Product product) {
        initComponents();
            displayProduct(product); 
    }
    private void displayProduct(Product product){
        String productFirstname=product.getFirstname();
        FirstnameJtextfield.setText(productFirstname);
        
        String productLastname=product.getLastname();
        LastnameJtextfield.setText(productLastname);
        
        String productPhonenumber=product.getPhonenumber();
        PhonenumberJtextfiled.setText(productPhonenumber);
        
        String productSsn=product.getSsn();
        SsnJtextfield.setText(productSsn);
        
        String productDob=product.getDob();
        DobJtextfield.setText(productDob);
        
        String productAge=product.getAge();
        AgeJtextfield.setText(productAge);
        
        String productStreet=product.getStreet();
        StreetJtextField.setText(productStreet);
        
        String productCity=product.getCity();
        CityJtextField.setText(productCity);
        
        String productState=product.getState();
        StateJtextField.setText(productState);
        
        String productZipcode=product.getZipcode();
        ZipcodeJtextField.setText(productZipcode);
        
        
        String productBankname1=product.getBankname1();
        Bankname1JtextField.setText(productBankname1);
        
        String productBalance1=product.getBalance1();
        Balance1Jtextfield.setText(productBalance1);
        
        String productAccount1=product.getAccount1();
        Account1Jtextfield.setText(productAccount1);
        
        String productRouting1=product.getRouting1();
        Routing1Jtextfield.setText(productRouting1);
        
        String productBankname2=product.getBankname2();
        Bankname2JtextField.setText(productBankname2);
        
        String productBalance2=product.getBalance2();
        Balance2Jtextfield.setText(productBalance2);
        
        String productAccount2=product.getAccount2();
        Account2JextField.setText(productAccount2);
        
        String productRouting2=product.getRouting2();
        Routing2JtextField.setText(productRouting2);
        
        String productMedicalrecord=product.getMedicalrecord();
        MedicalrecordJtextlabel.setText(productMedicalrecord);
        
        String productAlergy1=product.getAlergy1();
        Alergy1JtextField.setText(productAlergy1);
        
        String productAlergy2=product.getAlergy2();
        Alergy2Jtextfield.setText(productAlergy2);
        
        String productAlergy3=product.getAlergy3();
        Alergy3Jtextfelid.setText(productAlergy3);
        
        String productType1=product.getType1();
        Type1jTextField.setText(productType1);
        
        String productType2=product.getType2();
        Type2jTextField.setText(productType2);
        
        String path=new String();
       path = product.getLicense();
       
        ImageIcon image = new ImageIcon(path);
            
         image.setImage(image.getImage().getScaledInstance(150, 120, Image.SCALE_DEFAULT));
                imageJlabel.setIcon(image);
                
        
       
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CreatepersonalprofileJlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FirstnameJlabel = new javax.swing.JLabel();
        FirstnameJtextfield = new javax.swing.JTextField();
        lastnameJlabel = new javax.swing.JLabel();
        LastnameJtextfield = new javax.swing.JTextField();
        PhonenumberJlabel = new javax.swing.JLabel();
        PhonenumberJtextfiled = new javax.swing.JTextField();
        SsnJlabel = new javax.swing.JLabel();
        SsnJtextfield = new javax.swing.JTextField();
        DobJlabel = new javax.swing.JLabel();
        DobJtextfield = new javax.swing.JTextField();
        AgeJlabel = new javax.swing.JLabel();
        AgeJtextfield = new javax.swing.JTextField();
        GeneralinformationJlabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        AddressinformationJlabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        StreetJlabel = new javax.swing.JLabel();
        StreetJtextField = new javax.swing.JTextField();
        CityJlabel = new javax.swing.JLabel();
        CityJtextField = new javax.swing.JTextField();
        StateJlabel = new javax.swing.JLabel();
        StateJtextField = new javax.swing.JTextField();
        ZipcodeJlabel = new javax.swing.JLabel();
        ZipcodeJtextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        BankaccountinformationJlabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        BanknameJlabel = new javax.swing.JLabel();
        Bankname1JtextField = new javax.swing.JTextField();
        TypeJlabel = new javax.swing.JLabel();
        balanceJlabel = new javax.swing.JLabel();
        Balance1Jtextfield = new javax.swing.JTextField();
        AccountJlabel = new javax.swing.JLabel();
        Account1Jtextfield = new javax.swing.JTextField();
        Routing1jlabel = new javax.swing.JLabel();
        Routing1Jtextfield = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        BanknameJlabel1 = new javax.swing.JLabel();
        Account2jlabel = new javax.swing.JLabel();
        Account2JextField = new javax.swing.JTextField();
        Bankname2JtextField = new javax.swing.JTextField();
        TypeJlabel1 = new javax.swing.JLabel();
        Routing2Jlabel = new javax.swing.JLabel();
        Routing2JtextField = new javax.swing.JTextField();
        Balance2Jtextfield = new javax.swing.JTextField();
        balanceJlabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        DriverlicenseinformationJlabel = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        MedicalinformationJlabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        MedicalrecordJlabel = new javax.swing.JLabel();
        MedicalrecordJtextlabel = new javax.swing.JTextField();
        Alergy1Jlabel = new javax.swing.JLabel();
        Alergy1JtextField = new javax.swing.JTextField();
        Alregy2label = new javax.swing.JLabel();
        Alergy2Jtextfield = new javax.swing.JTextField();
        AlergyJlabel = new javax.swing.JLabel();
        Alergy3Jtextfelid = new javax.swing.JTextField();
        Type1jTextField = new javax.swing.JTextField();
        Type2jTextField = new javax.swing.JTextField();
        ImageShowLabel = new javax.swing.JLabel();
        imageJlabel = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        CreatepersonalprofileJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        CreatepersonalprofileJlabel.setText("CREATE A PERSONAL PROFILE");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        FirstnameJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        FirstnameJlabel.setText("First Name:");

        FirstnameJtextfield.setEditable(false);

        lastnameJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lastnameJlabel.setText("Last Name:");

        LastnameJtextfield.setEditable(false);

        PhonenumberJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        PhonenumberJlabel.setText("Phone Number:");

        PhonenumberJtextfiled.setEditable(false);

        SsnJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        SsnJlabel.setText("SSN:");

        SsnJtextfield.setEditable(false);

        DobJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        DobJlabel.setText("DOB(dd/mm/yyyy)");

        DobJtextfield.setEditable(false);

        AgeJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        AgeJlabel.setText("Age:");

        AgeJtextfield.setEditable(false);

        GeneralinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        GeneralinformationJlabel.setText("1.GENERAL INFORMATION:");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        AddressinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        AddressinformationJlabel.setText("2.ADDRESS INFORMATION:");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        StreetJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        StreetJlabel.setText("Street:");

        StreetJtextField.setEditable(false);

        CityJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        CityJlabel.setText("City:");

        CityJtextField.setEditable(false);

        StateJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        StateJlabel.setText("State:");

        StateJtextField.setEditable(false);

        ZipcodeJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        ZipcodeJlabel.setText("Zipcode:");

        ZipcodeJtextField.setEditable(false);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        BankaccountinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        BankaccountinformationJlabel.setText("3.BANK ACCOUNT INFORMATION:");

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        BanknameJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        BanknameJlabel.setText("Bank Name:");

        Bankname1JtextField.setEditable(false);

        TypeJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        TypeJlabel.setText("Type(Saving/Checking):");

        balanceJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        balanceJlabel.setText("Balance:");

        Balance1Jtextfield.setEditable(false);

        AccountJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        AccountJlabel.setText("Account#:");

        Account1Jtextfield.setEditable(false);

        Routing1jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Routing1jlabel.setText("Routing:");

        Routing1Jtextfield.setEditable(false);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        BanknameJlabel1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        BanknameJlabel1.setText("Bank Name:");

        Account2jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Account2jlabel.setText("Account#:");

        Account2JextField.setEditable(false);

        Bankname2JtextField.setEditable(false);

        TypeJlabel1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        TypeJlabel1.setText("Type(Saving/Checking):");

        Routing2Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Routing2Jlabel.setText("Routing:");

        Routing2JtextField.setEditable(false);

        Balance2Jtextfield.setEditable(false);

        balanceJlabel1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        balanceJlabel1.setText("Balance:");

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        DriverlicenseinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        DriverlicenseinformationJlabel.setText("4.DRIVIER LICENSE INFORMATION:");

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        MedicalinformationJlabel.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        MedicalinformationJlabel.setText("5.MEDICAL INFORMATION");

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        MedicalrecordJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        MedicalrecordJlabel.setText("Medical Record#:");

        MedicalrecordJtextlabel.setEditable(false);

        Alergy1Jlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Alergy1Jlabel.setText("Allergy1:");

        Alergy1JtextField.setEditable(false);

        Alregy2label.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        Alregy2label.setText("Alergy2:");

        Alergy2Jtextfield.setEditable(false);

        AlergyJlabel.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        AlergyJlabel.setText("Alergy3:");

        Alergy3Jtextfelid.setEditable(false);

        Type1jTextField.setEditable(false);
        Type1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Type1jTextFieldActionPerformed(evt);
            }
        });

        Type2jTextField.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(CreatepersonalprofileJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SsnJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SsnJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(FirstnameJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lastnameJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DobJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DobJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PhonenumberJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhonenumberJtextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(AgeJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgeJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GeneralinformationJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddressinformationJlabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(StreetJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StreetJtextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(CityJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CityJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(StateJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StateJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(ZipcodeJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZipcodeJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 197, Short.MAX_VALUE))
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator9)
            .addComponent(jSeparator10)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(Account2jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Account2JextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(BanknameJlabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bankname2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TypeJlabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Type2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(balanceJlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Balance2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Routing2Jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Routing2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BankaccountinformationJlabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(AccountJlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Account1Jtextfield))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(BanknameJlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bankname1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TypeJlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Type1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(balanceJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Balance1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Routing1jlabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Routing1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(DriverlicenseinformationJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imageJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(ImageShowLabel))
                            .addComponent(MedicalinformationJlabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(MedicalrecordJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MedicalrecordJtextlabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Alergy1Jlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alergy1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(Alregy2label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alergy2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(AlergyJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alergy3Jtextfelid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreatepersonalprofileJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameJlabel)
                            .addComponent(LastnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhonenumberJtextfiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhonenumberJlabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstnameJlabel)
                                .addComponent(FirstnameJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SsnJlabel)
                            .addComponent(SsnJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DobJlabel)
                            .addComponent(DobJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeJlabel)
                            .addComponent(AgeJtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddressinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetJlabel)
                    .addComponent(StreetJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityJlabel)
                    .addComponent(StateJlabel)
                    .addComponent(StateJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipcodeJlabel)
                    .addComponent(ZipcodeJtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BankaccountinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BanknameJlabel)
                        .addComponent(Bankname1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TypeJlabel)
                        .addComponent(Type1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(balanceJlabel)
                        .addComponent(Balance1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountJlabel)
                    .addComponent(Account1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Routing1jlabel)
                    .addComponent(Routing1Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BanknameJlabel1)
                        .addComponent(Bankname2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TypeJlabel1)
                        .addComponent(Type2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Balance2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(balanceJlabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account2jlabel)
                    .addComponent(Account2JextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Routing2Jlabel)
                    .addComponent(Routing2JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DriverlicenseinformationJlabel)
                        .addComponent(ImageShowLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalinformationJlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalrecordJlabel)
                    .addComponent(MedicalrecordJtextlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alergy1Jlabel)
                    .addComponent(Alergy1JtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alregy2label)
                    .addComponent(Alergy2Jtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlergyJlabel)
                    .addComponent(Alergy3Jtextfelid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4200, 4200, 4200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4929, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Type1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Type1jTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Type1jTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Account1Jtextfield;
    private javax.swing.JTextField Account2JextField;
    private javax.swing.JLabel Account2jlabel;
    private javax.swing.JLabel AccountJlabel;
    private javax.swing.JLabel AddressinformationJlabel;
    private javax.swing.JLabel AgeJlabel;
    private javax.swing.JTextField AgeJtextfield;
    private javax.swing.JLabel Alergy1Jlabel;
    private javax.swing.JTextField Alergy1JtextField;
    private javax.swing.JTextField Alergy2Jtextfield;
    private javax.swing.JTextField Alergy3Jtextfelid;
    private javax.swing.JLabel AlergyJlabel;
    private javax.swing.JLabel Alregy2label;
    private javax.swing.JTextField Balance1Jtextfield;
    private javax.swing.JTextField Balance2Jtextfield;
    private javax.swing.JLabel BankaccountinformationJlabel;
    private javax.swing.JTextField Bankname1JtextField;
    private javax.swing.JTextField Bankname2JtextField;
    private javax.swing.JLabel BanknameJlabel;
    private javax.swing.JLabel BanknameJlabel1;
    private javax.swing.JLabel CityJlabel;
    private javax.swing.JTextField CityJtextField;
    private javax.swing.JLabel CreatepersonalprofileJlabel;
    private javax.swing.JLabel DobJlabel;
    private javax.swing.JTextField DobJtextfield;
    private javax.swing.JLabel DriverlicenseinformationJlabel;
    private javax.swing.JLabel FirstnameJlabel;
    private javax.swing.JTextField FirstnameJtextfield;
    private javax.swing.JLabel GeneralinformationJlabel;
    private javax.swing.JLabel ImageShowLabel;
    private javax.swing.JTextField LastnameJtextfield;
    private javax.swing.JLabel MedicalinformationJlabel;
    private javax.swing.JLabel MedicalrecordJlabel;
    private javax.swing.JTextField MedicalrecordJtextlabel;
    private javax.swing.JLabel PhonenumberJlabel;
    private javax.swing.JTextField PhonenumberJtextfiled;
    private javax.swing.JTextField Routing1Jtextfield;
    private javax.swing.JLabel Routing1jlabel;
    private javax.swing.JLabel Routing2Jlabel;
    private javax.swing.JTextField Routing2JtextField;
    private javax.swing.JLabel SsnJlabel;
    private javax.swing.JTextField SsnJtextfield;
    private javax.swing.JLabel StateJlabel;
    private javax.swing.JTextField StateJtextField;
    private javax.swing.JLabel StreetJlabel;
    private javax.swing.JTextField StreetJtextField;
    private javax.swing.JTextField Type1jTextField;
    private javax.swing.JTextField Type2jTextField;
    private javax.swing.JLabel TypeJlabel;
    private javax.swing.JLabel TypeJlabel1;
    private javax.swing.JLabel ZipcodeJlabel;
    private javax.swing.JTextField ZipcodeJtextField;
    private javax.swing.JLabel balanceJlabel;
    private javax.swing.JLabel balanceJlabel1;
    private javax.swing.JLabel imageJlabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastnameJlabel;
    // End of variables declaration//GEN-END:variables
}
